verkehr:
    tags:
        - verkehr
    datasets: []
    queries:
        - "title:*verkehr*"
        
        
smart_city:
    tags:
        - digitale-transparenz-im-oeffentlichen-raum
        - dtoer
    datasets:
        - ted_taz_verkehrszaehlungen_werte_fussgaenger_velo
        - ugz_luftschadstoffmessung_stundenwerte


