verkehr:
    tags:
        - verkehr
    datasets: []
    queries:
        - "title:*verkehr*"
        
        
smart_city:
    tags:
        - digitale transparenz im öffentlichen raum
        - DTöR
    datasets:
        - sid_dav_verkehrszaehlung_miv_od2031
        - ted_taz_verkehrszaehlungen_werte_fussgaenger_velo
        - ugz_luftschadstoffmessung_stundenwerte


