name: Fetch badi counter

on:
  schedule:
    - cron:  '*/10 * * * *' # run every 20min

jobs:
  fetch_badi_counter:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: npm ci
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/automation-requirements.txt
        sudo apt update
        sudo apt-get install sqlite3

    - name: Fetch new data
      run: ./automation/badi-counter/run.sh
        
  
    - name: Commit and push to repo
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: GitHub Action Bot
        email: opendata@zuerich.ch
        commit-message: Update badi_counter.csv with latest data
        rebase: 'true'
