name: Generate documentation PDF

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create output directory
        run: mkdir output

      - uses: docker://pandoc/latex:2.9
        with:
          args: --from markdown+footnotes --table-of-contents --output=output/result.pdf docs/README.md docs/github_actions.md docs/ogd_processing.md docs/jupyter_notebooks.md 
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
