name: Generate documentation PDF

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create file list and output directory
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "::set-output name=files::$(printf '"%s" ' docs/??_*.md)"

      - uses: metaodi/pandoc-latex-action@v2.1
        with:
          args: >-
             -V colorlinks=true
             -V linkcolor=blue
             -V urlcolor=blue
             -V toc-title:"Inhaltsverzeichnis"
             --pdf-engine=xelatex
             --from markdown+footnotes+pipe_tables
             --table-of-contents 
             --output=output/result.pdf
             --template=ssz.tex
             --verbose
             ${{ steps.files_list.outputs.files }}
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
