name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 1 * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker for Repository
        id: lychee_repo
        uses: lycheeverse/lychee-action@v2
        with:
          args: --accept '200..=204, 429, 403, 500' --max-retries 5 --retry-wait-time 5 --suggest . --exclude 'https://data.integ.stadt-zuerich.ch/*|https://confluence-ssz.szh.loc*|https://github.com/opendatazurich/opendatazurich.github.io/settings/*' 
          fail: false

      - name: Download JSON
        run: curl --insecure -o data.json https://data.stadt-zuerich.ch/api/3/action/package_search?q=&rows=999

      - name: Extract Links from JSON
        run: |
          jq -r '..|.url? // empty' data.json > urls.txt

      - name: Link Checker for JSON
        run: |
          lychee --accept '200..=204, 429, 403, 500' --max-retries 5 --retry-wait-time 5 --suggest . < urls.txt
        id: lychee_json

      - name: Create Issue From File
        if: steps.lychee_repo.outputs.exit_code != 0 || steps.lychee_json.outcome != 'success'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
