name: Link Checker
# Checks URLs in Repo and creates issue, if url does not work
# see exclude list below
# https://data.integ.stadt-zuerich.ch is excluded due to SSL problems

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 1 * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker for Repository
        id: lychee_repo
        uses: lycheeverse/lychee-action@v2
        with:
          args: --accept '200..=204, 429, 403, 500' --max-retries 5 --retry-wait-time 5 --suggest . --exclude 'https://data.integ.stadt-zuerich.ch/*|https://confluence-ssz.szh.loc*|https://github.com/opendatazurich/opendatazurich.github.io/settings/*' 
          fail: false

      - name: Create Issue From File
        if: steps.lychee_repo.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
