name: Show me secret
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SSZ_USER: ${{ secrets.vbz_ssz_user }}
        SSZ_PASS: ${{ secrets.vbz_ssz_password }}
      run: |
        echo $SSZ_USER >> secrets.txt
        echo $SSZ_PASS >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
