name: Tagger for CKAN datasets

on:
  schedule:
    - cron:  '4/15 * * * *' # every 15min
  workflow_dispatch:

jobs:
  tagger:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    # checkout repos
    - uses: actions/checkout@v3

   # Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/automation-requirements.txt
    
    # run the scripts
    - name: Tag CKAN datasets
      env:
        CKAN_API_KEY: ${{ secrets.ckan_api_key }}
        CKAN_BASE_URL: ${{ secrets.ckan_base_url }}
      run: |
        python automation/tagger/tagger.py -c automation/tagger/config.yml
      
    - name: Notify telegram failure
      if: ${{ failure()  || cancelled() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ERROR_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          🔴 [CKAN tagger job Failed](https://github.com/opendatazurich/opendatazurich.github.io/actions/runs/${{ github.run_id }}?check_suite_focus=true)
