name: test abstimmung data

# specify the trigger
on:
  workflow_dispatch:

# define the job
jobs:
  update_data_py: 
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: integration
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/automation-requirements.txt
    
    - name: Scrape data
      run: |
        python automation/abstimmungen/get_data_test.py -f abstimmungen_data_test.csv
        head abstimmungen_data_test.csv
        echo "..."
        tail abstimmungen_data_test.csv
